name = "jiafutang"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "jiafutang_db"
database_name = "jiafutang-db"
database_id = "82f24d02-8c22-499f-b822-d28532c2a72b"

[observability]
enabled = true
